---
- name: Create test result File
  file: path={{regression_result_path}}/{{ item }} state=absent force=yes
  run_once: true
  with_items:
     - "{{ role_path|basename }}_result_1"
     - "{{ role_path|basename }}_raw_1"
  delegate_to: localhost

- name: Create test result File
  file: path={{regression_result_path}}/{{ item }} state=touch
  run_once: true
  with_items:
     - "{{ role_path|basename }}_result_1"
  delegate_to: localhost

- name: Execute 'openshift ex diagnostics'
  shell: openshift ex diagnostics > {{regression_result_path}}/{{ role_path|basename }}_raw_1
  ignore_errors: true

- name: Fetch raw result file
  fetch: src={{regression_result_path}}/{{ role_path|basename }}_raw_1 dest={{regression_result_path}}

- name: Filter result data
  shell: "egrep 'Errors|Warnings' {{regression_result_path}}/{{inventory_hostname}}/{{regression_result_path}}/{{ role_path|basename }}_raw_1|awk '{print $2 \" \" $4}' > {{regression_result_path}}/{{role_path|basename}}_result_1"
  register: openshift_ex_diagnostics_result
  delegate_to: localhost

- name: Generate report rule
  template: src=report_rule.json.j2 dest={{regression_result_path}}/{{ role_path|basename }}_rule
  delegate_to: localhost


