---
- name: Create test result files
  file: path={{regression_result_path}}/{{ item }} state=absent force=yes
  run_once: true
  with_items:
     - "{{ role_path|basename }}_result_1"
     - "{{ role_path|basename }}_raw_1"
  delegate_to: localhost

- name: Create test result files
  file: path={{regression_result_path}}/{{ item }} state=touch
  run_once: true
  with_items:
     - "{{ role_path|basename }}_result_1"
     - "{{ role_path|basename }}_raw_1"
  delegate_to: localhost

- name: Execute dig command to check dns can resolve ip.
  shell: dig "{{ item }}" | grep 'ANSWER SECTION' | wc -l
  with_items:
     - "{{groups['all']| unique}}"
  register: dig_result

- name: Generate test result
  shell: echo "{{ inventory_hostname }} {{ item.item }}  {{'FAIL' if item.stdout != '1' else 'SUCCESS' }}" >> {{regression_result_path}}/{{role_path|basename}}_raw_1
  with_items:
    - "{{dig_result.results}}"
  delegate_to: localhost

- name: Sort test result
  run_once: true
  shell: cat {{regression_result_path}}/{{role_path|basename}}_raw_1 | sort > {{regression_result_path}}/{{role_path|basename}}_result_1
  delegate_to: localhost
