---
- name: Create test result File
  file: path={{regression_result_path}}/{{ item }} state=absent force=yes
  run_once: true
  with_items:
     - "{{ role_path|basename }}"
     - "{{ role_path|basename }}_raw"
  delegate_to: localhost

- name: Create test result File
  file: path={{regression_result_path}}/{{ item }} state=touch
  run_once: true
  with_items:
     - "{{ role_path|basename }}"
  delegate_to: localhost

- name: Execute 'oc get node'
  shell: oc get node > {{regression_result_path}}/{{ role_path|basename }}_raw

- name: Fetch raw result file
  fetch: src={{regression_result_path}}/{{ role_path|basename }}_raw dest={{regression_result_path}}

- name: Filter result data
  shell: "cat {{regression_result_path}}/{{inventory_hostname}}/{{regression_result_path}}/{{ role_path|basename }}_raw|awk 'NF{NF--};1' > {{regression_result_path}}/{{role_path|basename}}"
  delegate_to: localhost




