---
- set_fact:
     project_name: "sample-hello-openshift"

- name: Delete test result File
  file: path={{regression_result_path}}/{{ item }} state=absent force=yes
  run_once: true
  with_items:
     - "{{ role_path|basename }}_result_1"
     - "{{ role_path|basename }}_raw_1"
     - "{{ role_path|basename }}_raw_2"
  delegate_to: localhost

- name: Create test result File
  file: path={{regression_result_path}}/{{ item }} state=touch
  run_once: true
  with_items:
     - "{{ role_path|basename }}_result_1"
  delegate_to: localhost

- name: Execute "curl" command to get SSL page
  get_url:
     url: "https://secure-hello-openshift.{{osm_default_subdomain}}"
     dest: "{{regression_result_path}}/{{ role_path|basename }}_raw_1"
     validate_certs: no
  delegate_to: localhost
  register: ssl_result
  ignore_errors: yes

- name: Execute "curl" command to get NON-SSL page
  get_url:
     url: "http://hello-openshift.{{osm_default_subdomain}}" 
     dest: "{{regression_result_path}}/{{ role_path|basename }}_raw_2"
     validate_certs: no
  delegate_to: localhost
  register: non_ssl_result
  ignore_errors: yes

- name: Generate result report - Clean up tested data
  shell: echo -n "$(echo '{{item}}'|grep -i OK |wc -l) " >> {{regression_result_path}}/{{ role_path|basename }}_result_1
  delegate_to: localhost
  with_items:
    - "{{ssl_result.msg}}"
    - "{{non_ssl_result.msg}}"

