---
- name: Create test result File
  file: path={{regression_result_path}}/{{ item }} state=absent force=yes
  run_once: true
  with_items:
     - "{{ role_path|basename }}"
     - "{{ role_path|basename }}_raw"
     - "{{ role_path|basename }}_before_temp"
  delegate_to: localhost

- name: Create test result File
  file: path={{regression_result_path}}/{{ item }} state=touch
  run_once: true
  with_items:
     - "{{ role_path|basename }}"
  delegate_to: localhost

- name: Execute 'oc get hostsubnet'
  shell: oc get hostsubnet 
  run_once: true
  delegate_to: "{{groups.masters.0}}"
  register: hostsubnet

- name: Fetch raw result file
  fetch: src={{regression_result_path}}/{{ role_path|basename }}_raw dest={{regression_result_path}}
  delegate_to: localhost

- name: Copy raw result file to all hosts
  copy: content="{{hostsubnet.stdout}}" dest="{{regression_result_path}}/{{ role_path|basename }}_raw"

- name: List up ping target list from hostsubnet information
  shell:  cat {{regression_result_path}}/{{ role_path|basename }}_raw |grep -iv NAME |grep -v $(hostname)|awk '{print $4}'|sed 's/0\/24/1/g'
  register: ping_target_list


- name: Execute Ping test
  shell: ping -c 1 {{ item }}|grep "packets transmitted" |awk '{print "{{inventory_hostname}} {{item}} "   $6}'  
  with_items:
     - "{{ping_target_list.stdout_lines}}"
  register: ping_test_result

- name: Generate result report 
  shell: "echo {{item.stdout}} >> {{regression_result_path}}/{{ role_path|basename }}_before_temp"
  delegate_to: localhost
  with_items:
     - "{{ping_test_result.results}}"

- name: Sort result report 
  shell: "sort {{regression_result_path}}/{{ role_path|basename }}_before_temp >>  {{regression_result_path}}/{{ role_path|basename }}"
  run_once: true
  delegate_to: localhost
