---
- name: Update virt_use_nfs/ virt_sandbox_use_nfs
  shell: setsebool -P {{item}}
  with_items:
    - "virt_use_nfs=true"
    - "virt_sandbox_use_nfs 1"

## If system is not registered, you should create this task according to your environment
#- name: Register Satellite
#  redhat_subscription: state=present org_id={{satellite.org}} environment={{satellite.environment}} activationkey={{satellite.activationkey}} autosubscribe=true
#  redhat_subscription: state=present org_id={{satellite.org}} environment={{satellite.environment}} username={{username}} password={{password}} autosubscribe=true 

- name: Register Satellite
  redhat_subscription: state=present  username='rhn-support-jlee' password='dlwnghABC!!22' 

- name: Manage Yum repositories for Openshift
  yum_repository: enabled={{item.enable}} name={{item.name}}
  with_items:
    - { name: "*", enable: "false" }
    - { name: "rhel-7-server-rpms", enable: "true" }
    - { name: "rhel-7-server-satellite-tools-6.1-rpms", enable: "true" }
    - { name: "rhel-7-server-extras-rpms", enable: "true" }
    - { name: "rhel-7-server-ose-3.2-rpms", enable: "true" }

- name: Install Essential Packages
  package: name={{ item }} state=present use=yum
  with_items:
    - "wget"
    - "git"
    - "net-tools"
    - "bind-utils" 
    - "iptables-services"
    - "bridge-utils"
    - "bash-completion"
    - "nfs-utils"

  
