
---
 - include: ../common/master_config_facts.yaml
 - include: ../sample_app/hello_openshift.yaml

 - name: Check if deploying application with ImageStream (no build)
   hosts: masters[0]
   gather_facts: false
   
   pre_tasks:
   - name: set concurrent path
     local_action: command pwd
     register: pwd

   - name: set_facts - pwd_path
     set_fact:
        pwd_path: "{{pwd.stdout}}"

   - name: Wait for deploying Hello Openshift application.
     uri: url=https://{{hello_openshift_certs.hostname}} validate_certs=no return_content=yes status_code=200 timeout=300
     register: deployed_test_app
     delegate_to: "{{ groups.masters.0 if remote_test_host == ' ' else remote_test_host}}"
     until: deployed_test_app.content.find("Hello OpenShift!") != -1
     retries: 50
     delay: 10

   roles:
    - { role: reg_imageStream_deploy  } 


