
---
 - include: ../common/master_config_facts.yaml
 - name: Check internal registry via router - oc login/docker login/docker push/docker pull
   hosts: masters[0]
   gather_facts: false
   become: true
   
   pre_tasks:
   - name: set concurrent path
     local_action: command pwd
     register: pwd

   - name: set_facts - pwd_path
     set_fact:
        pwd_path: "{{pwd.stdout}}"

   roles:
    - { role: reg_internal_registry_check } 


