
---
 - include: ../common/master_config_facts.yaml
 - name: Check if local storage has enough spaces. Full of /var, /var/log, /var/lib/docker and docker-pool can impact OCP. 
   hosts: all
   gather_facts: false
   
   pre_tasks:
   - name: set concurrent path
     local_action: command pwd
     register: pwd

   - name: set_facts - pwd_path
     set_fact:
        pwd_path: "{{pwd.stdout}}"

   roles:
    - { role: reg_local_storage_check } 


