
---
 - include: ../common/master_config_facts.yaml
 - name: Execute Openshift diagnostics command 
   hosts: masters[0]
   gather_facts: false
   
   pre_tasks:
   - name: set concurrent path
     local_action: command pwd
     register: pwd

   - name: set_facts - pwd_path
     set_fact:
        pwd_path: "{{pwd.stdout}}"

   roles:
    - { role: reg_openshift_diagnostics_cmd } 


