
---
 - include: ../common/master_config_facts.yaml
# - include: ../sample_app/eap_ssl.yaml

 - name: Check if S2I build is working properly
   hosts: masters[0]
   gather_facts: false
   
   pre_tasks:
   - name: set concurrent path
     local_action: command pwd
     register: pwd

   - name: set_facts - pwd_path
     set_fact:
        pwd_path: "{{pwd.stdout}}"

   - name: Wait for deploying EAP application.
     wait_for: host="secure-eap-app-test.{{osm_default_subdomain}}" port="443" state="started" delay="1"
     delegate_to: "{{ groups.masters.0 if remote_test_host == ' ' else remote_test_host}}"

   roles:
    - { role: reg_s2i_build  } 


