
---
 - include: ../common/master_config_facts.yaml
 - name: Before start regression test, it will backup previous data and to be ready for go.
   hosts: all
   gather_facts: false
   
   pre_tasks:
   - name: Get timestamp
     local_action: command  date +"%Y%m%d_%H%M%S"
     register: date

   tasks:
   - name: Check if result folder exist
     stat: path={{regression_result_path}} 
     run_once: true
     register: result_folder

   - name: Create history directory
     run_once: true
     local_action: file path="{{regression_result_path}}_history/" state="directory"
     when: "{{result_folder.stat.exists == True}}"

   - name: Backup previous result directory
     run_once: true
     local_action: command cp -R "{{regression_result_path}}/" "{{regression_result_path}}_history/{{date.stdout}}/" 
     when: "{{result_folder.stat.exists == True}}"

   - name: Delete result folder for localhost
     run_once: true
     local_action: file path="{{regression_result_path}}" state=absent force=yes
     ignore_errors: yes
     
   - name: Create result folder for localhost
     run_once: true
     local_action: file path="{{regression_result_path}}" state=directory 
     ignore_errors: yes

   - name: Delete result folders on OCP clusters      
     file: path="{{regression_result_path}}" state=absent force=yes recurse=yes
     ignore_errors: yes
   
   - name: Create result folder on OCP clusters
     file: path="{{regression_result_path}}" state=directory 
     ignore_errors: yes
   
