---
- name: Create test result File
  file: path={{regression_result_path}}/{{ item }} state=absent force=yes
  run_once: true
  with_items:
     - "{{ role_path|basename }}_result_1"
     - "{{ role_path|basename }}_raw_1"
  delegate_to: localhost

- name: Create test result File
  file: path={{regression_result_path}}/{{ item }} state=touch
  run_once: true
  with_items:
     - "{{ role_path|basename }}_result_1"
  delegate_to: localhost

- name: Api server health check on masters
  shell: "curl -k https://localhost:8443/healthz" 
  register: api_health_check

- name: Generate result report 
  shell: "echo {{inventory_hostname}} {{item.stdout}} >> {{regression_result_path}}/{{ role_path|basename }}_result_1"
  delegate_to: localhost
  with_items:
     - "{{api_health_check}}"


