---
- name: Create test result File
  file: path={{regression_result_path}}/{{ item }} state=absent force=yes
  run_once: true
  with_items:
     - "{{ role_path|basename }}_result_1"
     - "{{ role_path|basename }}_raw_1"
     - "{{ role_path|basename }}_temp_1"
  delegate_to: localhost

- name: Create test result File
  file: path={{regression_result_path}}/{{ item }} state=touch
  run_once: true
  with_items:
     - "{{ role_path|basename }}_result_1"
     - "{{ role_path|basename }}_raw_1"
     - "{{ role_path|basename }}_temp_1"
  delegate_to: localhost

- name: Api server health check on masters
  shell: curl -k https://localhost:8443/healthz
  ignore_errors: yes
  register: api_health_check

- name: Generate result report 
  shell: "echo {{inventory_hostname}} \\'{{item.cmd}}\\'  {{item.stdout}} >> {{regression_result_path}}/{{ role_path|basename }}_raw_1"
  delegate_to: localhost
  with_items:
     - "{{api_health_check}}"

- name: Generate result report 
  shell: "echo {{inventory_hostname}} {{'FAIL' if item.stdout != 'ok' else 'SUCCESS' }} >> {{regression_result_path}}/{{ role_path|basename }}_temp_1"
  delegate_to: localhost
  with_items:
     - "{{api_health_check}}"

- name: Sort docker pull image result report
  shell: sort {{regression_result_path}}/{{ role_path|basename }}_temp_1 -o  {{regression_result_path}}/{{ role_path|basename }}_result_1
  delegate_to: localhost

- name: Generate report rule
  template: src=report_rule.json.j2 dest={{regression_result_path}}/{{ role_path|basename }}_rule
  delegate_to: localhost

