---
- name: Create test result File
  file: path={{regression_result_path}}/{{ item }} state=absent force=yes
  run_once: true
  with_items:
     - "{{ role_path|basename }}"
     - "{{ role_path|basename }}_raw"
  delegate_to: localhost

- name: Create test result File
  file: path={{regression_result_path}}/{{ item }} state=touch
  run_once: true
  with_items:
     - "{{ role_path|basename }}"
  delegate_to: localhost

- name: Execute 'df command'
  shell: "df -h > {{regression_result_path}}/{{ role_path|basename }}_raw"

- name: Execute 'lvs command'
  shell:  "lvs  |grep docker-pool |awk '{print \"lvm 0 0 0 \" int($5 + $6) \"% \" $1} '  >>  {{regression_result_path}}/{{ role_path|basename }}_raw "

- name: Fetch raw result file
  fetch: src={{regression_result_path}}/{{ role_path|basename }}_raw dest={{regression_result_path}}

- name: Load the raw data
  command: cat  {{regression_result_path}}/{{inventory_hostname}}/{{regression_result_path}}/{{ role_path|basename }}_raw
  register: raw_data
  delegate_to: localhost

- name: Copy sort_report.sh template
  template: src=sort_report.sh.j2 dest="{{regression_result_path}}/{{inventory_hostname}}/{{regression_result_path}}/{{ role_path|basename }}-sort_report.sh" mode=0777 
  delegate_to: localhost

- name: Execute sort_report.sh to generate final result
  script: "{{regression_result_path}}/{{inventory_hostname}}/{{regression_result_path}}/{{ role_path|basename }}-sort_report.sh"
  delegate_to: localhost




