apiVersion: v1
kind: Template
metadata:
  name: hello-openshift
objects:
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      name: hello-openshift
    name: hello-openshift
  spec:
    ports:
      - port: 8080
        targetPort: 8080
    selector:
      name: hello-openshift
    type: LoadBalancer
- apiVersion: v1
  kind: Pod
  metadata:
    name: hello-openshift
    creationTimestamp:
    labels:
      name: hello-openshift
  spec:
    containers:
    - name: hello-openshift
      image: openshift/hello-openshift
      ports:
      - containerPort: 8080
        protocol: TCP
      resources: {}
      volumeMounts:
      - name: tmp
        mountPath: "/tmp"
      terminationMessagePath: "/dev/termination-log"
      imagePullPolicy: IfNotPresent
      capabilities: {}
      securityContext:
        capabilities: {}
        privileged: false
    volumes:
    - name: tmp
      emptyDir: {}
    restartPolicy: Always
    dnsPolicy: ClusterFirst
    serviceAccount: ''
  status: {}

