---
 - name: Check if api server is running via health check url
   hosts: localhost
   gather_facts: false

   pre_tasks:
   - name: set concurrent path
     local_action: command pwd
     register: pwd

   - name: set_facts - pwd_path
     set_fact:
        pwd_path: "{{pwd.stdout}}"

   tasks:
    - reg_report: title="test" path="/tmp"


