---
- set_fact:
     project_name: "sample-eap-ssl"

- name: Delete test result File
  file: path={{regression_result_path}}/{{ item }} state=absent force=yes
  run_once: true
  with_items:
     - "{{ role_path|basename }}_eap_ssl.cnf"
     - "keystore.jks"
     - "{{ role_path|basename }}_eap-service-account.yaml"
  delegate_to: localhost

- name: Execute `oc login`
  shell: "{{ item }}"
  with_items:
    - "oc login -u '{{oc_login.user_id}}' -p '{{oc_login_password}}' --insecure-skip-tls-verify --server={{oc_login.url}}"
  delegate_to: "{{ groups.masters.0 if remote_test_host == ' ' else remote_test_host}}"

- name: Check if test project exist
  shell: "oc project {{project_name}}"
  ignore_errors: true
  register: test_project_exist
  delegate_to: "{{ groups.masters.0 if remote_test_host == ' ' else remote_test_host}}"

- name: Create test project if it does not exist
  shell: " oc new-project {{project_name}} "
  when: test_project_exist|failed
  delegate_to: "{{ groups.masters.0 if remote_test_host == ' ' else remote_test_host}}"

- name: Delete EAP secret and sa
  shell: " {{ item }} "
  when: test_project_exist|success
  delegate_to: "{{ groups.masters.0 if remote_test_host == ' ' else remote_test_host}}"
  ignore_errors: true
  with_items:
    - " oc delete secret eap-app-secret"
    - " oc delete sa eap-service-account"
    - " oc delete all -l app=eap-app-test"

- name: Generate Self Sign Certs
  command: keytool -genkey -keyalg RSA -alias selfsigned -keystore {{regression_result_path}}/keystore.jks -storepass supersecret -keypass supersecret -validity 360 -keysize 2048  -dname 'cn=secure-eap-app-test.{{osm_default_subdomain}}, ou=Consult, o=Red Hat, l=Toronto, st=Ontario c=CA'
  delegate_to: localhost
  register: generate_self_sign_cer

- name: Change jks file permission
  file: path={{regression_result_path}}/keystore.jks mode=777
  delegate_to: localhost

- name: Copy eap-service-account.yaml to regression_test folder
  copy: src="{{item.src}}" dest="{{item.dest}}" force="yes"
  with_items:
      - { src: "eap-service-account.yaml" , dest: "{{regression_result_path}}/{{ role_path|basename }}_eap-service-account.yaml"}
      - { src: "{{regression_result_path}}/keystore.jks", dest: "{{regression_result_path}}/keystore.jks" }
  delegate_to: "{{ groups.masters.0 if remote_test_host == ' ' else remote_test_host}}"

- name: Create secret/sa
  command: "{{ item }}"
  args:  
    chdir: "{{regression_result_path}}"
  with_items:
     - "oc secrets new eap-app-secret {{regression_result_path}}/keystore.jks"
     - "oc create -f {{regression_result_path}}/{{ role_path|basename }}_eap-service-account.yaml"
  delegate_to: "{{ groups.masters.0 if remote_test_host == ' ' else remote_test_host}}"

- name: Deploy eap application
  command: "oc new-app --template=eap64-https-s2i -p HTTPS_NAME=selfsigned,HTTPS_PASSWORD=supersecret,HOSTNAME_HTTPS=secure-eap-app-test.{{osm_default_subdomain}},HOSTNAME_HTTP=eap-app-test.{{osm_default_subdomain}} -l app=eap-app-test"
  register: deploy_eap_app
  delegate_to: "{{ groups.masters.0 if remote_test_host == ' ' else remote_test_host}}"

- name: Delete test result File
  file: path={{regression_result_path}}/{{ item }} state=absent force=yes
  run_once: true
  with_items:
     - "{{ role_path|basename }}_eap_ssl.cnf"
     - "keystore.jks"
     - "{{ role_path|basename }}_eap-service-account.yaml"
  delegate_to: localhost

